search_ajax:
  path: /search/ajax/{queryString}
  defaults: {queryString: ''}
  controller: Setono\SyliusElasticsearchPlugin\Controller\SearchController::searchAjaxAction

search_list:
  path: /search/{queryString}
  defaults: {queryString: ''}
  controller: Setono\SyliusElasticsearchPlugin\Controller\SearchController::searchListAction

sylius_shop_product_results:
  path: /taxons/{slug}/results
  methods: [GET]
  defaults:
    _controller: Setono\SyliusElasticsearchPlugin\Controller\SearchController::searchTaxonResultsAction
  requirements:
    slug: .+

sylius_shop_product_index:
  path: /taxons/{slug}
  methods: [GET]
  defaults:
    _controller: Setono\SyliusElasticsearchPlugin\Controller\SearchController::searchTaxonAction
  requirements:
    slug: .+
